name: Slither

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

jobs:
  slither:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: yarn install

      - name: Compile contracts
        run: yarn compile

      - name: Run Slither
        uses: crytic/slither-action@main
        id: slither
        continue-on-error: true
        with:
          ignore-compile: true
          node-version: "18"

    #   - name: Upload SARIF file
    #     uses: github/codeql-action/upload-sarif@v2
    #     with:
    #         sarif_file: ${{ steps.slither.outputs.sarif }}
